/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcknowledgementsRouteImport } from './routes/acknowledgements'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as MunBuilderRouteImport } from './routes/mun-builder'
import { Route as PathwayRouteImport } from './routes/pathway'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as SpeechWritingRouteImport } from './routes/speech-writing'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as VocabularyRouteImport } from './routes/vocabulary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcknowledgementsRoute = AcknowledgementsRouteImport.update({
  id: '/acknowledgements',
  path: '/acknowledgements',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const MunBuilderRoute = MunBuilderRouteImport.update({
  id: '/mun-builder',
  path: '/mun-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwayRoute = PathwayRouteImport.update({
  id: '/pathway',
  path: '/pathway',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechWritingRoute = SpeechWritingRouteImport.update({
  id: '/speech-writing',
  path: '/speech-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/builder': typeof BuilderRoute
  '/checklist': typeof ChecklistRoute
  '/coach': typeof CoachRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/journey': typeof JourneyRoute
  '/mentor': typeof MentorRoute
  '/mistakes': typeof MistakesRoute
  '/mun-builder': typeof MunBuilderRoute
  '/pathway': typeof PathwayRoute
  '/practice': typeof PracticeRoute
  '/quotes': typeof QuotesRoute
  '/resources': typeof ResourcesRoute
  '/skills': typeof SkillsRoute
  '/speakers': typeof SpeakersRoute
  '/speech-writing': typeof SpeechWritingRoute
  '/tips': typeof TipsRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/builder': typeof BuilderRoute
  '/checklist': typeof ChecklistRoute
  '/coach': typeof CoachRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/journey': typeof JourneyRoute
  '/mentor': typeof MentorRoute
  '/mistakes': typeof MistakesRoute
  '/mun-builder': typeof MunBuilderRoute
  '/pathway': typeof PathwayRoute
  '/practice': typeof PracticeRoute
  '/quotes': typeof QuotesRoute
  '/resources': typeof ResourcesRoute
  '/skills': typeof SkillsRoute
  '/speakers': typeof SpeakersRoute
  '/speech-writing': typeof SpeechWritingRoute
  '/tips': typeof TipsRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/builder': typeof BuilderRoute
  '/checklist': typeof ChecklistRoute
  '/coach': typeof CoachRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/journey': typeof JourneyRoute
  '/mentor': typeof MentorRoute
  '/mistakes': typeof MistakesRoute
  '/mun-builder': typeof MunBuilderRoute
  '/pathway': typeof PathwayRoute
  '/practice': typeof PracticeRoute
  '/quotes': typeof QuotesRoute
  '/resources': typeof ResourcesRoute
  '/skills': typeof SkillsRoute
  '/speakers': typeof SpeakersRoute
  '/speech-writing': typeof SpeechWritingRoute
  '/tips': typeof TipsRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acknowledgements'
    | '/builder'
    | '/checklist'
    | '/coach'
    | '/competitions'
    | '/dashboard'
    | '/faq'
    | '/guide'
    | '/journey'
    | '/mentor'
    | '/mistakes'
    | '/mun-builder'
    | '/pathway'
    | '/practice'
    | '/quotes'
    | '/resources'
    | '/skills'
    | '/speakers'
    | '/speech-writing'
    | '/tips'
    | '/vocabulary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acknowledgements'
    | '/builder'
    | '/checklist'
    | '/coach'
    | '/competitions'
    | '/dashboard'
    | '/faq'
    | '/guide'
    | '/journey'
    | '/mentor'
    | '/mistakes'
    | '/mun-builder'
    | '/pathway'
    | '/practice'
    | '/quotes'
    | '/resources'
    | '/skills'
    | '/speakers'
    | '/speech-writing'
    | '/tips'
    | '/vocabulary'
  id:
    | '__root__'
    | '/'
    | '/acknowledgements'
    | '/builder'
    | '/checklist'
    | '/coach'
    | '/competitions'
    | '/dashboard'
    | '/faq'
    | '/guide'
    | '/journey'
    | '/mentor'
    | '/mistakes'
    | '/mun-builder'
    | '/pathway'
    | '/practice'
    | '/quotes'
    | '/resources'
    | '/skills'
    | '/speakers'
    | '/speech-writing'
    | '/tips'
    | '/vocabulary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcknowledgementsRoute: typeof AcknowledgementsRoute
  BuilderRoute: typeof BuilderRoute
  ChecklistRoute: typeof ChecklistRoute
  CoachRoute: typeof CoachRoute
  CompetitionsRoute: typeof CompetitionsRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  GuideRoute: typeof GuideRoute
  JourneyRoute: typeof JourneyRoute
  MentorRoute: typeof MentorRoute
  MistakesRoute: typeof MistakesRoute
  MunBuilderRoute: typeof MunBuilderRoute
  PathwayRoute: typeof PathwayRoute
  PracticeRoute: typeof PracticeRoute
  QuotesRoute: typeof QuotesRoute
  ResourcesRoute: typeof ResourcesRoute
  SkillsRoute: typeof SkillsRoute
  SpeakersRoute: typeof SpeakersRoute
  SpeechWritingRoute: typeof SpeechWritingRoute
  TipsRoute: typeof TipsRoute
  VocabularyRoute: typeof VocabularyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acknowledgements': {
      id: '/acknowledgements'
      path: '/acknowledgements'
      fullPath: '/acknowledgements'
      preLoaderRoute: typeof AcknowledgementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mun-builder': {
      id: '/mun-builder'
      path: '/mun-builder'
      fullPath: '/mun-builder'
      preLoaderRoute: typeof MunBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathway': {
      id: '/pathway'
      path: '/pathway'
      fullPath: '/pathway'
      preLoaderRoute: typeof PathwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech-writing': {
      id: '/speech-writing'
      path: '/speech-writing'
      fullPath: '/speech-writing'
      preLoaderRoute: typeof SpeechWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcknowledgementsRoute: AcknowledgementsRoute,
  BuilderRoute: BuilderRoute,
  ChecklistRoute: ChecklistRoute,
  CoachRoute: CoachRoute,
  CompetitionsRoute: CompetitionsRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  GuideRoute: GuideRoute,
  JourneyRoute: JourneyRoute,
  MentorRoute: MentorRoute,
  MistakesRoute: MistakesRoute,
  MunBuilderRoute: MunBuilderRoute,
  PathwayRoute: PathwayRoute,
  PracticeRoute: PracticeRoute,
  QuotesRoute: QuotesRoute,
  ResourcesRoute: ResourcesRoute,
  SkillsRoute: SkillsRoute,
  SpeakersRoute: SpeakersRoute,
  SpeechWritingRoute: SpeechWritingRoute,
  TipsRoute: TipsRoute,
  VocabularyRoute: VocabularyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
